substitutions:
  # This Web Tools YAML is intended to be placed in the repo's firmware/ directory.
  # The project root is therefore one level up.
  bc7215_project_dir: "../.."
  project_version: "1.6.2"


esphome:
  name: bc7215-ac-ctrl
  friendly_name: BC7215 AC CONTROLLER
  name_add_mac_suffix: true
  project:
    name: "timj-code.bc7215_ac"
    version: ${project_version}
  includes:
    # BC7215 C++ ESP-IDF wrappers
    - ${bc7215_project_dir}/deps/bc7215_ac_lib/examples/ESP-IDF/components/bc7215/bc7215.cpp
    - ${bc7215_project_dir}/deps/bc7215_ac_lib/examples/ESP-IDF/components/bc7215ac/bc7215ac.cpp

    # BC7215 C library
    - ${bc7215_project_dir}/deps/bc7215_ac_lib/bc7215_ac_lib/bc7215_lib.c
    - ${bc7215_project_dir}/deps/bc7215_ac_lib/bc7215_ac_lib/bc7215_ac_lib.c

    # C++ wrapper headers
    - ${bc7215_project_dir}/deps/bc7215_ac_lib/examples/ESP-IDF/components/bc7215/include/bc7215.hpp
    - ${bc7215_project_dir}/deps/bc7215_ac_lib/examples/ESP-IDF/components/bc7215ac/include/bc7215ac.hpp

    # C library headers
    - ${bc7215_project_dir}/deps/bc7215_ac_lib/bc7215_ac_lib/bc7215_lib.h
    - ${bc7215_project_dir}/deps/bc7215_ac_lib/bc7215_ac_lib/bc7215_ac_lib.h
    - ${bc7215_project_dir}/deps/bc7215_ac_lib/bc7215_ac_lib/bc7215_types.h

    # Your ESP-IDF-specific BC7215 configuration
    - ${bc7215_project_dir}/deps/bc7215_ac_lib/examples/ESP-IDF/main/include/bc7215_lib_config.h


esp32:
  variant: esp32
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: ${bc7215_project_dir}/components
    components: [bc7215_ac]

logger:

api:

ota:
  platform: esphome

wifi:
  ap: 
    ssid: "BC7215_AC_Setup_psw_12345678"
    password: "12345678"
    ap_timeout: 1min

captive_portal:

improv_serial:

climate:
  - platform: bc7215_ac
    id: ac_controller
    name: "AC"

    bc7215_uart_num: 1
    bc7215_tx_pin: GPIO16	# ESP32 RX pin
    bc7215_rx_pin: GPIO17	# ESP32 TX pin
    bc7215_busy_pin: GPIO18
    bc7215_mod_pin: GPIO19

    library_temperature_unit: C

    visual:
      min_temperature: 16
      max_temperature: 30
      temperature_step: 1

button:
  - platform: template
    name: "Pair Button"
    on_press:
      - lambda: |-
          id(ac_controller).start_pairing();

  - platform: template
    name: "Alt Button"
    on_press:
      - lambda: |-
          id(ac_controller).builtin_or_next();

text_sensor:
  - platform: template
    name: "Status"
    update_interval: 1s
    lambda: |-
      return {id(ac_controller).status_message()};

preferences:
  flash_write_interval: 1s
