substitutions:
  # This Web Tools YAML is intended to be placed in the repo's firmware/ directory.
  # The project root is therefore one level up.
  bc7215_project_dir: ..
  project_version: "1.2.0"

esphome:
  name: bc7215-ac-ctrl
  friendly_name: BC7215 AC CONTROLLER
  name_add_mac_suffix: true
  project:
    name: "timj-code.bc7215_ac"
    version: ${project_version}
  platformio_options:
    extra_scripts:
      - pre:../../../../components/bc7215_ac/add_bc7215_sources.py


esp32:
  variant: esp32c3
  framework:
    type: esp-idf

external_components:
  - source:
      type: local
      path: ../components
    components: [bc7215_ac]

logger:

api:

ota:
  platform: esphome

wifi:
  ap: {}

captive_portal:

improv_serial:

climate:
  - platform: bc7215_ac
    id: ac_controller
    name: "AC"

    bc7215_uart_num: 1
    bc7215_tx_pin: GPIO4
    bc7215_rx_pin: GPIO3
    bc7215_busy_pin: GPIO1
    bc7215_mod_pin: GPIO0

    library_temperature_unit: C

    visual:
      min_temperature: 16
      max_temperature: 30
      temperature_step: 1

button:
  - platform: template
    name: "Pair Button"
    on_press:
      - lambda: |-
          id(ac_controller).start_pairing();

  - platform: template
    name: "Alt Button"
    on_press:
      - lambda: |-
          id(ac_controller).builtin_or_next();

text_sensor:
  - platform: template
    name: "Status"
    update_interval: 1s
    lambda: |-
      return {id(ac_controller).status_message()};

preferences:
  flash_write_interval: 1s
